const SUCCESS_CODE = 200;
const CREATED = 201;
const ACCEPTED = 202;
const NO_CONTENT = 204;
const MOVED_PERMANENTLY = 301;
const FOUND = 302;
const NOT_MODIFIED = 304;
const BAD_REQUEST = 400;
const UN_AUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;
const REQUEST_TIMEOUT = 408;
const CONFLICT = 409;
const UNSUPPORTED_MEDIA_TYPE = 415;
const TOO_MANY_REQUESTS = 429;
const SERVER_ERROR = 500;
const SERVICE_UNAVAILABLE = 503;
const PARTIAL_CONTENT_SUCCESS = 206;
const SESSION_EXPIRED = 440;
const DATA_ALREADY_EXISTS = 409;

module.exports = {
  SUCCESS_CODE,
  CREATED,
  ACCEPTED,
  NO_CONTENT,
  MOVED_PERMANENTLY,
  FOUND,
  NOT_MODIFIED,
  BAD_REQUEST,
  UN_AUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  REQUEST_TIMEOUT,
  CONFLICT,
  UNSUPPORTED_MEDIA_TYPE,
  TOO_MANY_REQUESTS,
  SERVER_ERROR,
  SERVICE_UNAVAILABLE,
  PARTIAL_CONTENT_SUCCESS,
  SESSION_EXPIRED,
  DATA_ALREADY_EXISTS
};
